services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  api-product:
    container_name: api-product
    build:
      context: ./api_product
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - mongo

  api-order:
    container_name: api-order
    build:
      context: ./api_order
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - mongo

  api-user:
    container_name: api-user
    build:
      context: ./api_user
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  backend:
